### ISSUE TITLE
Status of lms

### ISSUE THREAD

**Issue by javadba** [scala-lms/summer-of-lms-2014#1]
This is more of an email: feel free to get upset with this issue and respond in a different location/way ;)  I am quite interested in the goals of this project and the current progress. Is the project active with ongoing development? Where is the github repo for the actual source? Seems to be a tutorial repo and this summer-o-lms .. but what is the "main" one?

**Comment by TiarkRompf** [comment]
Please see the main website: http://scala-lms.github.io. There is a section "Community" with links to mailing lists etc.
